// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/firehydrant/api-client-go/models"
)

// GetV1SchedulesReader is a Reader for the GetV1Schedules structure.
type GetV1SchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1SchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1SchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1SchedulesOK creates a GetV1SchedulesOK with default headers values
func NewGetV1SchedulesOK() *GetV1SchedulesOK {
	return &GetV1SchedulesOK{}
}

/*GetV1SchedulesOK handles this case with default header values.

translation missing: en.api.schedules.list.description
*/
type GetV1SchedulesOK struct {
	Payload *models.ScheduleEntity
}

func (o *GetV1SchedulesOK) Error() string {
	return fmt.Sprintf("[GET /v1/schedules][%d] getV1SchedulesOK  %+v", 200, o.Payload)
}

func (o *GetV1SchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScheduleEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
