// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/firehydrant/api-client-go/models"
)

// GetV1IntegrationsAwsCloudtrailBatchesReader is a Reader for the GetV1IntegrationsAwsCloudtrailBatches structure.
type GetV1IntegrationsAwsCloudtrailBatchesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1IntegrationsAwsCloudtrailBatchesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1IntegrationsAwsCloudtrailBatchesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1IntegrationsAwsCloudtrailBatchesOK creates a GetV1IntegrationsAwsCloudtrailBatchesOK with default headers values
func NewGetV1IntegrationsAwsCloudtrailBatchesOK() *GetV1IntegrationsAwsCloudtrailBatchesOK {
	return &GetV1IntegrationsAwsCloudtrailBatchesOK{}
}

/*GetV1IntegrationsAwsCloudtrailBatchesOK handles this case with default header values.

translation missing: en.api.integrations.aws.cloudtrail_batches.list.description
*/
type GetV1IntegrationsAwsCloudtrailBatchesOK struct {
	Payload *models.CloudtrailBatchEntityPaginated
}

func (o *GetV1IntegrationsAwsCloudtrailBatchesOK) Error() string {
	return fmt.Sprintf("[GET /v1/integrations/aws/cloudtrail_batches][%d] getV1IntegrationsAwsCloudtrailBatchesOK  %+v", 200, o.Payload)
}

func (o *GetV1IntegrationsAwsCloudtrailBatchesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudtrailBatchEntityPaginated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
