// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1IntegrationsAwsCloudtrailBatchesIDParams creates a new GetV1IntegrationsAwsCloudtrailBatchesIDParams object
// with the default values initialized.
func NewGetV1IntegrationsAwsCloudtrailBatchesIDParams() *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	var ()
	return &GetV1IntegrationsAwsCloudtrailBatchesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1IntegrationsAwsCloudtrailBatchesIDParamsWithTimeout creates a new GetV1IntegrationsAwsCloudtrailBatchesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1IntegrationsAwsCloudtrailBatchesIDParamsWithTimeout(timeout time.Duration) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	var ()
	return &GetV1IntegrationsAwsCloudtrailBatchesIDParams{

		timeout: timeout,
	}
}

// NewGetV1IntegrationsAwsCloudtrailBatchesIDParamsWithContext creates a new GetV1IntegrationsAwsCloudtrailBatchesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1IntegrationsAwsCloudtrailBatchesIDParamsWithContext(ctx context.Context) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	var ()
	return &GetV1IntegrationsAwsCloudtrailBatchesIDParams{

		Context: ctx,
	}
}

// NewGetV1IntegrationsAwsCloudtrailBatchesIDParamsWithHTTPClient creates a new GetV1IntegrationsAwsCloudtrailBatchesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1IntegrationsAwsCloudtrailBatchesIDParamsWithHTTPClient(client *http.Client) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	var ()
	return &GetV1IntegrationsAwsCloudtrailBatchesIDParams{
		HTTPClient: client,
	}
}

/*GetV1IntegrationsAwsCloudtrailBatchesIDParams contains all the parameters to send to the API endpoint
for the get v1 integrations aws cloudtrail batches Id operation typically these are written to a http.Request
*/
type GetV1IntegrationsAwsCloudtrailBatchesIDParams struct {

	/*ID
	  Batch UUID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) WithTimeout(timeout time.Duration) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) WithContext(ctx context.Context) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) WithHTTPClient(client *http.Client) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) WithID(id string) *GetV1IntegrationsAwsCloudtrailBatchesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 integrations aws cloudtrail batches Id params
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
