// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/firehydrant/api-client-go/models"
)

// GetV1IntegrationsAwsCloudtrailBatchesIDReader is a Reader for the GetV1IntegrationsAwsCloudtrailBatchesID structure.
type GetV1IntegrationsAwsCloudtrailBatchesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1IntegrationsAwsCloudtrailBatchesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1IntegrationsAwsCloudtrailBatchesIDOK creates a GetV1IntegrationsAwsCloudtrailBatchesIDOK with default headers values
func NewGetV1IntegrationsAwsCloudtrailBatchesIDOK() *GetV1IntegrationsAwsCloudtrailBatchesIDOK {
	return &GetV1IntegrationsAwsCloudtrailBatchesIDOK{}
}

/*GetV1IntegrationsAwsCloudtrailBatchesIDOK handles this case with default header values.

translation missing: en.api.integrations.aws.cloudtrail_batches.retrieve.description
*/
type GetV1IntegrationsAwsCloudtrailBatchesIDOK struct {
	Payload *models.CloudtrailBatchEntity
}

func (o *GetV1IntegrationsAwsCloudtrailBatchesIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/integrations/aws/cloudtrail_batches/{id}][%d] getV1IntegrationsAwsCloudtrailBatchesIdOK  %+v", 200, o.Payload)
}

func (o *GetV1IntegrationsAwsCloudtrailBatchesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudtrailBatchEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
