// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetV1IntegrationsAwsCloudtrailBatchesIDEventsReader is a Reader for the GetV1IntegrationsAwsCloudtrailBatchesIDEvents structure.
type GetV1IntegrationsAwsCloudtrailBatchesIDEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1IntegrationsAwsCloudtrailBatchesIDEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1IntegrationsAwsCloudtrailBatchesIDEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1IntegrationsAwsCloudtrailBatchesIDEventsOK creates a GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK with default headers values
func NewGetV1IntegrationsAwsCloudtrailBatchesIDEventsOK() *GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK {
	return &GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK{}
}

/*GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK handles this case with default header values.

get Event(s)
*/
type GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK struct {
}

func (o *GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK) Error() string {
	return fmt.Sprintf("[GET /v1/integrations/aws/cloudtrail_batches/{id}/events][%d] getV1IntegrationsAwsCloudtrailBatchesIdEventsOK ", 200)
}

func (o *GetV1IntegrationsAwsCloudtrailBatchesIDEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
