// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewPatchV1IntegrationsConfluenceCloudConnectionsIDParams creates a new PatchV1IntegrationsConfluenceCloudConnectionsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1IntegrationsConfluenceCloudConnectionsIDParams() *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	return &PatchV1IntegrationsConfluenceCloudConnectionsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1IntegrationsConfluenceCloudConnectionsIDParamsWithTimeout creates a new PatchV1IntegrationsConfluenceCloudConnectionsIDParams object
// with the ability to set a timeout on a request.
func NewPatchV1IntegrationsConfluenceCloudConnectionsIDParamsWithTimeout(timeout time.Duration) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	return &PatchV1IntegrationsConfluenceCloudConnectionsIDParams{
		timeout: timeout,
	}
}

// NewPatchV1IntegrationsConfluenceCloudConnectionsIDParamsWithContext creates a new PatchV1IntegrationsConfluenceCloudConnectionsIDParams object
// with the ability to set a context for a request.
func NewPatchV1IntegrationsConfluenceCloudConnectionsIDParamsWithContext(ctx context.Context) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	return &PatchV1IntegrationsConfluenceCloudConnectionsIDParams{
		Context: ctx,
	}
}

// NewPatchV1IntegrationsConfluenceCloudConnectionsIDParamsWithHTTPClient creates a new PatchV1IntegrationsConfluenceCloudConnectionsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1IntegrationsConfluenceCloudConnectionsIDParamsWithHTTPClient(client *http.Client) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	return &PatchV1IntegrationsConfluenceCloudConnectionsIDParams{
		HTTPClient: client,
	}
}

/* PatchV1IntegrationsConfluenceCloudConnectionsIDParams contains all the parameters to send to the API endpoint
   for the patch v1 integrations confluence cloud connections Id operation.

   Typically these are written to a http.Request.
*/
type PatchV1IntegrationsConfluenceCloudConnectionsIDParams struct {

	// V1IntegrationsConfluenceCloudConnections.
	V1IntegrationsConfluenceCloudConnections *models.PatchV1IntegrationsConfluenceCloudConnections

	/* ID.

	   Connection UUID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 integrations confluence cloud connections Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WithDefaults() *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 integrations confluence cloud connections Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WithTimeout(timeout time.Duration) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WithContext(ctx context.Context) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WithHTTPClient(client *http.Client) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithV1IntegrationsConfluenceCloudConnections adds the v1IntegrationsConfluenceCloudConnections to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WithV1IntegrationsConfluenceCloudConnections(v1IntegrationsConfluenceCloudConnections *models.PatchV1IntegrationsConfluenceCloudConnections) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	o.SetV1IntegrationsConfluenceCloudConnections(v1IntegrationsConfluenceCloudConnections)
	return o
}

// SetV1IntegrationsConfluenceCloudConnections adds the v1IntegrationsConfluenceCloudConnections to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) SetV1IntegrationsConfluenceCloudConnections(v1IntegrationsConfluenceCloudConnections *models.PatchV1IntegrationsConfluenceCloudConnections) {
	o.V1IntegrationsConfluenceCloudConnections = v1IntegrationsConfluenceCloudConnections
}

// WithID adds the id to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WithID(id string) *PatchV1IntegrationsConfluenceCloudConnectionsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch v1 integrations confluence cloud connections Id params
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.V1IntegrationsConfluenceCloudConnections != nil {
		if err := r.SetBodyParam(o.V1IntegrationsConfluenceCloudConnections); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
