// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// PatchV1IntegrationsConfluenceCloudConnectionsIDReader is a Reader for the PatchV1IntegrationsConfluenceCloudConnectionsID structure.
type PatchV1IntegrationsConfluenceCloudConnectionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1IntegrationsConfluenceCloudConnectionsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchV1IntegrationsConfluenceCloudConnectionsIDOK creates a PatchV1IntegrationsConfluenceCloudConnectionsIDOK with default headers values
func NewPatchV1IntegrationsConfluenceCloudConnectionsIDOK() *PatchV1IntegrationsConfluenceCloudConnectionsIDOK {
	return &PatchV1IntegrationsConfluenceCloudConnectionsIDOK{}
}

/* PatchV1IntegrationsConfluenceCloudConnectionsIDOK describes a response with status code 200, with default header values.

Update the given Confluence integration connection.
*/
type PatchV1IntegrationsConfluenceCloudConnectionsIDOK struct {
	Payload *models.ConnectionEntity
}

func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/integrations/confluence_cloud/connections/{id}][%d] patchV1IntegrationsConfluenceCloudConnectionsIdOK  %+v", 200, o.Payload)
}
func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDOK) GetPayload() *models.ConnectionEntity {
	return o.Payload
}

func (o *PatchV1IntegrationsConfluenceCloudConnectionsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConnectionEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
