// Code generated by go-swagger; DO NOT EDIT.

package saved_searches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteV1SavedSearchesResourceTypeSavedSearchIDReader is a Reader for the DeleteV1SavedSearchesResourceTypeSavedSearchID structure.
type DeleteV1SavedSearchesResourceTypeSavedSearchIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1SavedSearchesResourceTypeSavedSearchIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent creates a DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent with default headers values
func NewDeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent() *DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent {
	return &DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent{}
}

/*DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent handles this case with default header values.

Delete a specific saved search
*/
type DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent struct {
}

func (o *DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/saved_searches/{resource_type}/{saved_search_id}][%d] deleteV1SavedSearchesResourceTypeSavedSearchIdNoContent ", 204)
}

func (o *DeleteV1SavedSearchesResourceTypeSavedSearchIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
