// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new incidents API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for incidents API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DeleteV1IncidentsIncidentID archives an incident

Archives an incident which will hide it from lists and metrics
*/
func (a *Client) DeleteV1IncidentsIncidentID(params *DeleteV1IncidentsIncidentIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteV1IncidentsIncidentIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1IncidentsIncidentIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteV1IncidentsIncidentId",
		Method:             "DELETE",
		PathPattern:        "/v1/incidents/{incident_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1IncidentsIncidentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteV1IncidentsIncidentIDOK), nil

}

/*
DeleteV1IncidentsIncidentIDAlertsIncidentAlertID Remove an alert from the incident
*/
func (a *Client) DeleteV1IncidentsIncidentIDAlertsIncidentAlertID(params *DeleteV1IncidentsIncidentIDAlertsIncidentAlertIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteV1IncidentsIncidentIDAlertsIncidentAlertIDNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1IncidentsIncidentIDAlertsIncidentAlertIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteV1IncidentsIncidentIdAlertsIncidentAlertId",
		Method:             "DELETE",
		PathPattern:        "/v1/incidents/{incident_id}/alerts/{incident_alert_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1IncidentsIncidentIDAlertsIncidentAlertIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteV1IncidentsIncidentIDAlertsIncidentAlertIDNoContent), nil

}

/*
DeleteV1IncidentsIncidentIDEventsEventIDStars Remove a star from an incident event
*/
func (a *Client) DeleteV1IncidentsIncidentIDEventsEventIDStars(params *DeleteV1IncidentsIncidentIDEventsEventIDStarsParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteV1IncidentsIncidentIDEventsEventIDStarsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1IncidentsIncidentIDEventsEventIDStarsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteV1IncidentsIncidentIdEventsEventIdStars",
		Method:             "DELETE",
		PathPattern:        "/v1/incidents/{incident_id}/events/{event_id}/stars",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1IncidentsIncidentIDEventsEventIDStarsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteV1IncidentsIncidentIDEventsEventIDStarsNoContent), nil

}

/*
DeleteV1IncidentsIncidentIDImpactTypeID Remove a piece of infrastructure from an incident as impact
*/
func (a *Client) DeleteV1IncidentsIncidentIDImpactTypeID(params *DeleteV1IncidentsIncidentIDImpactTypeIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteV1IncidentsIncidentIDImpactTypeIDNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1IncidentsIncidentIDImpactTypeIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteV1IncidentsIncidentIdImpactTypeId",
		Method:             "DELETE",
		PathPattern:        "/v1/incidents/{incident_id}/impact/{type}/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1IncidentsIncidentIDImpactTypeIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteV1IncidentsIncidentIDImpactTypeIDNoContent), nil

}

/*
DeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentID unassigns a role

Unassign a role from a user. Any tasks that were created on the incident will remain in whatever state they are in
*/
func (a *Client) DeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentID(params *DeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteV1IncidentsIncidentIdRoleAssignmentsRoleAssignmentId",
		Method:             "DELETE",
		PathPattern:        "/v1/incidents/{incident_id}/role_assignments/{role_assignment_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteV1IncidentsIncidentIDRoleAssignmentsRoleAssignmentIDOK), nil

}

/*
GetV1Incidents Retrieve incidents
*/
func (a *Client) GetV1Incidents(params *GetV1IncidentsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1Incidents",
		Method:             "GET",
		PathPattern:        "/v1/incidents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsOK), nil

}

/*
GetV1IncidentsIncidentID Retrieve an incident
*/
func (a *Client) GetV1IncidentsIncidentID(params *GetV1IncidentsIncidentIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentId",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDOK), nil

}

/*
GetV1IncidentsIncidentIDAlerts Retrieve alerts that are linked to the incident
*/
func (a *Client) GetV1IncidentsIncidentIDAlerts(params *GetV1IncidentsIncidentIDAlertsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDAlertsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDAlertsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdAlerts",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/alerts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDAlertsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDAlertsOK), nil

}

/*
GetV1IncidentsIncidentIDChannel get v1 incidents incident Id channel API
*/
func (a *Client) GetV1IncidentsIncidentIDChannel(params *GetV1IncidentsIncidentIDChannelParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDChannelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDChannelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdChannel",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/channel",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDChannelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDChannelOK), nil

}

/*
GetV1IncidentsIncidentIDCounts get v1 incidents incident Id counts API
*/
func (a *Client) GetV1IncidentsIncidentIDCounts(params *GetV1IncidentsIncidentIDCountsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDCountsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDCountsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdCounts",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/counts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDCountsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDCountsOK), nil

}

/*
GetV1IncidentsIncidentIDEvents Retrieve the timeline for an incident
*/
func (a *Client) GetV1IncidentsIncidentIDEvents(params *GetV1IncidentsIncidentIDEventsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDEventsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDEventsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdEvents",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/events",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDEventsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDEventsOK), nil

}

/*
GetV1IncidentsIncidentIDEventsEventID Get an individual incident event
*/
func (a *Client) GetV1IncidentsIncidentIDEventsEventID(params *GetV1IncidentsIncidentIDEventsEventIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDEventsEventIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDEventsEventIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdEventsEventId",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/events/{event_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDEventsEventIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDEventsEventIDOK), nil

}

/*
GetV1IncidentsIncidentIDEventsEventIDStars Get all stars for an incident event
*/
func (a *Client) GetV1IncidentsIncidentIDEventsEventIDStars(params *GetV1IncidentsIncidentIDEventsEventIDStarsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDEventsEventIDStarsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDEventsEventIDStarsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdEventsEventIdStars",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/events/{event_id}/stars",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDEventsEventIDStarsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDEventsEventIDStarsOK), nil

}

/*
GetV1IncidentsIncidentIDImpactType Retrieve impacted infrastructure for the type on the incident
*/
func (a *Client) GetV1IncidentsIncidentIDImpactType(params *GetV1IncidentsIncidentIDImpactTypeParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDImpactTypeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDImpactTypeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdImpactType",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/impact/{type}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDImpactTypeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDImpactTypeOK), nil

}

/*
GetV1IncidentsIncidentIDMilestones Retrieve all milestones for an incident
*/
func (a *Client) GetV1IncidentsIncidentIDMilestones(params *GetV1IncidentsIncidentIDMilestonesParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDMilestonesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDMilestonesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdMilestones",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/milestones",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDMilestonesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDMilestonesOK), nil

}

/*
GetV1IncidentsIncidentIDRelatedChangeEvents Retrieve all change events that have been associated to the incident
*/
func (a *Client) GetV1IncidentsIncidentIDRelatedChangeEvents(params *GetV1IncidentsIncidentIDRelatedChangeEventsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDRelatedChangeEventsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDRelatedChangeEventsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdRelatedChangeEvents",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/related_change_events",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDRelatedChangeEventsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDRelatedChangeEventsOK), nil

}

/*
GetV1IncidentsIncidentIDRoleAssignments lists all assignees

Retrieve a list of all of the current role assignments for the incident
*/
func (a *Client) GetV1IncidentsIncidentIDRoleAssignments(params *GetV1IncidentsIncidentIDRoleAssignmentsParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDRoleAssignmentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDRoleAssignmentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdRoleAssignments",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/role_assignments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDRoleAssignmentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDRoleAssignmentsOK), nil

}

/*
GetV1IncidentsIncidentIDTasks Retrieve tasks for the incident
*/
func (a *Client) GetV1IncidentsIncidentIDTasks(params *GetV1IncidentsIncidentIDTasksParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDTasksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDTasksParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdTasks",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/tasks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDTasksReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDTasksOK), nil

}

/*
GetV1IncidentsIncidentIDUsersUserID Retrieve a user with current roles for an incident
*/
func (a *Client) GetV1IncidentsIncidentIDUsersUserID(params *GetV1IncidentsIncidentIDUsersUserIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetV1IncidentsIncidentIDUsersUserIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1IncidentsIncidentIDUsersUserIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getV1IncidentsIncidentIdUsersUserId",
		Method:             "GET",
		PathPattern:        "/v1/incidents/{incident_id}/users/{user_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1IncidentsIncidentIDUsersUserIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetV1IncidentsIncidentIDUsersUserIDOK), nil

}

/*
PatchV1IncidentsIncidentID Update an incident
*/
func (a *Client) PatchV1IncidentsIncidentID(params *PatchV1IncidentsIncidentIDParams, authInfo runtime.ClientAuthInfoWriter) (*PatchV1IncidentsIncidentIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchV1IncidentsIncidentIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchV1IncidentsIncidentId",
		Method:             "PATCH",
		PathPattern:        "/v1/incidents/{incident_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchV1IncidentsIncidentIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchV1IncidentsIncidentIDOK), nil

}

/*
PatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimary Assign an alert a primary status
*/
func (a *Client) PatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimary(params *PatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimaryParams, authInfo runtime.ClientAuthInfoWriter) (*PatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimaryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimaryParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchV1IncidentsIncidentIdAlertsIncidentAlertIdPrimary",
		Method:             "PATCH",
		PathPattern:        "/v1/incidents/{incident_id}/alerts/{incident_alert_id}/primary",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimaryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchV1IncidentsIncidentIDAlertsIncidentAlertIDPrimaryOK), nil

}

/*
PatchV1IncidentsIncidentIDNotesNoteID Update a note
*/
func (a *Client) PatchV1IncidentsIncidentIDNotesNoteID(params *PatchV1IncidentsIncidentIDNotesNoteIDParams, authInfo runtime.ClientAuthInfoWriter) (*PatchV1IncidentsIncidentIDNotesNoteIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchV1IncidentsIncidentIDNotesNoteIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchV1IncidentsIncidentIdNotesNoteId",
		Method:             "PATCH",
		PathPattern:        "/v1/incidents/{incident_id}/notes/{note_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchV1IncidentsIncidentIDNotesNoteIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchV1IncidentsIncidentIDNotesNoteIDOK), nil

}

/*
PatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventID Update a change event
*/
func (a *Client) PatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventID(params *PatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventIDParams, authInfo runtime.ClientAuthInfoWriter) (*PatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchV1IncidentsIncidentIdRelatedChangeEventsRelatedChangeEventId",
		Method:             "PATCH",
		PathPattern:        "/v1/incidents/{incident_id}/related_change_events/{related_change_event_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchV1IncidentsIncidentIDRelatedChangeEventsRelatedChangeEventIDOK), nil

}

/*
PatchV1IncidentsIncidentIDTasksTaskID Update a task
*/
func (a *Client) PatchV1IncidentsIncidentIDTasksTaskID(params *PatchV1IncidentsIncidentIDTasksTaskIDParams, authInfo runtime.ClientAuthInfoWriter) (*PatchV1IncidentsIncidentIDTasksTaskIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchV1IncidentsIncidentIDTasksTaskIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchV1IncidentsIncidentIdTasksTaskId",
		Method:             "PATCH",
		PathPattern:        "/v1/incidents/{incident_id}/tasks/{task_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchV1IncidentsIncidentIDTasksTaskIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PatchV1IncidentsIncidentIDTasksTaskIDOK), nil

}

/*
PostV1Incidents Create an incident
*/
func (a *Client) PostV1Incidents(params *PostV1IncidentsParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1Incidents",
		Method:             "POST",
		PathPattern:        "/v1/incidents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsCreated), nil

}

/*
PostV1IncidentsIncidentIDAlerts Assign alerts to an incident
*/
func (a *Client) PostV1IncidentsIncidentIDAlerts(params *PostV1IncidentsIncidentIDAlertsParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDAlertsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDAlertsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdAlerts",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/alerts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDAlertsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDAlertsNoContent), nil

}

/*
PostV1IncidentsIncidentIDAttachments Upload a file to the incident
*/
func (a *Client) PostV1IncidentsIncidentIDAttachments(params *PostV1IncidentsIncidentIDAttachmentsParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDAttachmentsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDAttachmentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdAttachments",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/attachments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDAttachmentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDAttachmentsCreated), nil

}

/*
PostV1IncidentsIncidentIDImpactType Add a piece of infrastructure to an incident as impact
*/
func (a *Client) PostV1IncidentsIncidentIDImpactType(params *PostV1IncidentsIncidentIDImpactTypeParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDImpactTypeCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDImpactTypeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdImpactType",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/impact/{type}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDImpactTypeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDImpactTypeCreated), nil

}

/*
PostV1IncidentsIncidentIDNotes Add a note to an incident
*/
func (a *Client) PostV1IncidentsIncidentIDNotes(params *PostV1IncidentsIncidentIDNotesParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDNotesCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDNotesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdNotes",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/notes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDNotesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDNotesCreated), nil

}

/*
PostV1IncidentsIncidentIDRelatedChangeEvents Associate a change event to the incident
*/
func (a *Client) PostV1IncidentsIncidentIDRelatedChangeEvents(params *PostV1IncidentsIncidentIDRelatedChangeEventsParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDRelatedChangeEventsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDRelatedChangeEventsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdRelatedChangeEvents",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/related_change_events",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDRelatedChangeEventsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDRelatedChangeEventsCreated), nil

}

/*
PostV1IncidentsIncidentIDRoleAssignments assigns a role

Assign a role to a user for this incident. All tasks associated to the role will also automatically be attached
*/
func (a *Client) PostV1IncidentsIncidentIDRoleAssignments(params *PostV1IncidentsIncidentIDRoleAssignmentsParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDRoleAssignmentsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDRoleAssignmentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdRoleAssignments",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/role_assignments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDRoleAssignmentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDRoleAssignmentsCreated), nil

}

/*
PostV1IncidentsIncidentIDTeamAssignments Assign a team to an incident for the incident
*/
func (a *Client) PostV1IncidentsIncidentIDTeamAssignments(params *PostV1IncidentsIncidentIDTeamAssignmentsParams, authInfo runtime.ClientAuthInfoWriter) (*PostV1IncidentsIncidentIDTeamAssignmentsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1IncidentsIncidentIDTeamAssignmentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "postV1IncidentsIncidentIdTeamAssignments",
		Method:             "POST",
		PathPattern:        "/v1/incidents/{incident_id}/team_assignments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1IncidentsIncidentIDTeamAssignmentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV1IncidentsIncidentIDTeamAssignmentsCreated), nil

}

/*
PutV1IncidentsIncidentIDEventsEventIDStars Star an incident event
*/
func (a *Client) PutV1IncidentsIncidentIDEventsEventIDStars(params *PutV1IncidentsIncidentIDEventsEventIDStarsParams, authInfo runtime.ClientAuthInfoWriter) (*PutV1IncidentsIncidentIDEventsEventIDStarsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1IncidentsIncidentIDEventsEventIDStarsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "putV1IncidentsIncidentIdEventsEventIdStars",
		Method:             "PUT",
		PathPattern:        "/v1/incidents/{incident_id}/events/{event_id}/stars",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1IncidentsIncidentIDEventsEventIDStarsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutV1IncidentsIncidentIDEventsEventIDStarsOK), nil

}

/*
PutV1IncidentsIncidentIDMilestonesBulkUpdate Update a list of milestones on an incident
*/
func (a *Client) PutV1IncidentsIncidentIDMilestonesBulkUpdate(params *PutV1IncidentsIncidentIDMilestonesBulkUpdateParams, authInfo runtime.ClientAuthInfoWriter) (*PutV1IncidentsIncidentIDMilestonesBulkUpdateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1IncidentsIncidentIDMilestonesBulkUpdateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "putV1IncidentsIncidentIdMilestonesBulkUpdate",
		Method:             "PUT",
		PathPattern:        "/v1/incidents/{incident_id}/milestones/bulk_update",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1IncidentsIncidentIDMilestonesBulkUpdateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutV1IncidentsIncidentIDMilestonesBulkUpdateOK), nil

}

/*
PutV1IncidentsIncidentIDResolve Resolve an active incident
*/
func (a *Client) PutV1IncidentsIncidentIDResolve(params *PutV1IncidentsIncidentIDResolveParams, authInfo runtime.ClientAuthInfoWriter) (*PutV1IncidentsIncidentIDResolveOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutV1IncidentsIncidentIDResolveParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "putV1IncidentsIncidentIdResolve",
		Method:             "PUT",
		PathPattern:        "/v1/incidents/{incident_id}/resolve",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutV1IncidentsIncidentIDResolveReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PutV1IncidentsIncidentIDResolveOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
