// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/firehydrant/api-client-go/models"
)

// PutV1IncidentsIncidentIDResolveReader is a Reader for the PutV1IncidentsIncidentIDResolve structure.
type PutV1IncidentsIncidentIDResolveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutV1IncidentsIncidentIDResolveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutV1IncidentsIncidentIDResolveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutV1IncidentsIncidentIDResolveOK creates a PutV1IncidentsIncidentIDResolveOK with default headers values
func NewPutV1IncidentsIncidentIDResolveOK() *PutV1IncidentsIncidentIDResolveOK {
	return &PutV1IncidentsIncidentIDResolveOK{}
}

/*PutV1IncidentsIncidentIDResolveOK handles this case with default header values.

Resolve an active incident
*/
type PutV1IncidentsIncidentIDResolveOK struct {
	Payload *models.IncidentEntity
}

func (o *PutV1IncidentsIncidentIDResolveOK) Error() string {
	return fmt.Sprintf("[PUT /v1/incidents/{incident_id}/resolve][%d] putV1IncidentsIncidentIdResolveOK  %+v", 200, o.Payload)
}

func (o *PutV1IncidentsIncidentIDResolveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IncidentEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
