// Code generated by go-swagger; DO NOT EDIT.

package severity_matrix

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/firehydrant/api-client-go/models"
)

// PatchV1SeverityMatrixReader is a Reader for the PatchV1SeverityMatrix structure.
type PatchV1SeverityMatrixReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1SeverityMatrixReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchV1SeverityMatrixOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchV1SeverityMatrixOK creates a PatchV1SeverityMatrixOK with default headers values
func NewPatchV1SeverityMatrixOK() *PatchV1SeverityMatrixOK {
	return &PatchV1SeverityMatrixOK{}
}

/*PatchV1SeverityMatrixOK handles this case with default header values.

translation missing: en.api.severity_matrix.update.description
*/
type PatchV1SeverityMatrixOK struct {
	Payload *models.SeverityMatrixItemEntity
}

func (o *PatchV1SeverityMatrixOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/severity_matrix][%d] patchV1SeverityMatrixOK  %+v", 200, o.Payload)
}

func (o *PatchV1SeverityMatrixOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SeverityMatrixItemEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
