// Code generated by go-swagger; DO NOT EDIT.

package post_mortems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostV1PostMortemsReportsReportIDPublishParams creates a new PostV1PostMortemsReportsReportIDPublishParams object
// with the default values initialized.
func NewPostV1PostMortemsReportsReportIDPublishParams() *PostV1PostMortemsReportsReportIDPublishParams {
	var ()
	return &PostV1PostMortemsReportsReportIDPublishParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1PostMortemsReportsReportIDPublishParamsWithTimeout creates a new PostV1PostMortemsReportsReportIDPublishParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostV1PostMortemsReportsReportIDPublishParamsWithTimeout(timeout time.Duration) *PostV1PostMortemsReportsReportIDPublishParams {
	var ()
	return &PostV1PostMortemsReportsReportIDPublishParams{

		timeout: timeout,
	}
}

// NewPostV1PostMortemsReportsReportIDPublishParamsWithContext creates a new PostV1PostMortemsReportsReportIDPublishParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostV1PostMortemsReportsReportIDPublishParamsWithContext(ctx context.Context) *PostV1PostMortemsReportsReportIDPublishParams {
	var ()
	return &PostV1PostMortemsReportsReportIDPublishParams{

		Context: ctx,
	}
}

// NewPostV1PostMortemsReportsReportIDPublishParamsWithHTTPClient creates a new PostV1PostMortemsReportsReportIDPublishParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostV1PostMortemsReportsReportIDPublishParamsWithHTTPClient(client *http.Client) *PostV1PostMortemsReportsReportIDPublishParams {
	var ()
	return &PostV1PostMortemsReportsReportIDPublishParams{
		HTTPClient: client,
	}
}

/*PostV1PostMortemsReportsReportIDPublishParams contains all the parameters to send to the API endpoint
for the post v1 post mortems reports report Id publish operation typically these are written to a http.Request
*/
type PostV1PostMortemsReportsReportIDPublishParams struct {

	/*ReportID*/
	ReportID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) WithTimeout(timeout time.Duration) *PostV1PostMortemsReportsReportIDPublishParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) WithContext(ctx context.Context) *PostV1PostMortemsReportsReportIDPublishParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) WithHTTPClient(client *http.Client) *PostV1PostMortemsReportsReportIDPublishParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReportID adds the reportID to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) WithReportID(reportID string) *PostV1PostMortemsReportsReportIDPublishParams {
	o.SetReportID(reportID)
	return o
}

// SetReportID adds the reportId to the post v1 post mortems reports report Id publish params
func (o *PostV1PostMortemsReportsReportIDPublishParams) SetReportID(reportID string) {
	o.ReportID = reportID
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1PostMortemsReportsReportIDPublishParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param report_id
	if err := r.SetPathParam("report_id", o.ReportID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
