// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PatchV1IntegrationsAwsCloudtrailBatches translation missing: en.api.integrations.aws.cloudtrail_batches.update.description
// swagger:model patchV1IntegrationsAwsCloudtrailBatches
type PatchV1IntegrationsAwsCloudtrailBatches struct {

	// error
	Error string `json:"error,omitempty"`

	// events created
	EventsCreated int32 `json:"events_created,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this patch v1 integrations aws cloudtrail batches
func (m *PatchV1IntegrationsAwsCloudtrailBatches) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchV1IntegrationsAwsCloudtrailBatches) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchV1IntegrationsAwsCloudtrailBatches) UnmarshalBinary(b []byte) error {
	var res PatchV1IntegrationsAwsCloudtrailBatches
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
