// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchV1IntegrationsConfluenceCloudConnections Update the given Confluence integration connection.
//
// swagger:model patchV1IntegrationsConfluenceCloudConnections
type PatchV1IntegrationsConfluenceCloudConnections struct {

	// default space key
	DefaultSpaceKey string `json:"default_space_key,omitempty"`
}

// Validate validates this patch v1 integrations confluence cloud connections
func (m *PatchV1IntegrationsConfluenceCloudConnections) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this patch v1 integrations confluence cloud connections based on context it is used
func (m *PatchV1IntegrationsConfluenceCloudConnections) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchV1IntegrationsConfluenceCloudConnections) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchV1IntegrationsConfluenceCloudConnections) UnmarshalBinary(b []byte) error {
	var res PatchV1IntegrationsConfluenceCloudConnections
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
