// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SeverityMatrixItemEntity translation missing: en.api.severity_matrix.retrieve.description
// swagger:model SeverityMatrixItemEntity
type SeverityMatrixItemEntity struct {

	// condition
	Condition string `json:"condition,omitempty"`

	// impact
	Impact string `json:"impact,omitempty"`

	// severity
	Severity string `json:"severity,omitempty"`
}

// Validate validates this severity matrix item entity
func (m *SeverityMatrixItemEntity) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SeverityMatrixItemEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeverityMatrixItemEntity) UnmarshalBinary(b []byte) error {
	var res SeverityMatrixItemEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
